service: template-serverless-typescript-jest-cleanarchitecture-circieci

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs6.10

functions:
  hello:
    handler: src/adapters/controllers/handler.hello
    events:
      - http:
          method: get
          path: hello
